# Form implementation generated from reading ui file 'designer/form.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(439, 353)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label)
        self.chooseVideoButton = QtWidgets.QPushButton(Dialog)
        self.chooseVideoButton.setObjectName("chooseVideoButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.chooseVideoButton)
        self.videoPathLabel = QtWidgets.QLabel(Dialog)
        self.videoPathLabel.setText("")
        self.videoPathLabel.setObjectName("videoPathLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.videoPathLabel)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_2)
        self.chooseSubtitleButton = QtWidgets.QPushButton(Dialog)
        self.chooseSubtitleButton.setObjectName("chooseSubtitleButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.chooseSubtitleButton)
        self.subtitlePathLabel = QtWidgets.QLabel(Dialog)
        self.subtitlePathLabel.setText("")
        self.subtitlePathLabel.setObjectName("subtitlePathLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.subtitlePathLabel)
        self.durationTimeEdit = QtWidgets.QTimeEdit(Dialog)
        self.durationTimeEdit.setObjectName("durationTimeEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.durationTimeEdit)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_4)
        self.chooseFolderButton = QtWidgets.QPushButton(Dialog)
        self.chooseFolderButton.setObjectName("chooseFolderButton")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.chooseFolderButton)
        self.outputPathLabel = QtWidgets.QLabel(Dialog)
        self.outputPathLabel.setText("")
        self.outputPathLabel.setObjectName("outputPathLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.ItemRole.LabelRole, self.outputPathLabel)
        self.processButton = QtWidgets.QPushButton(Dialog)
        self.processButton.setObjectName("processButton")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.processButton)
        self.statusLabel = QtWidgets.QLabel(Dialog)
        self.statusLabel.setText("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.statusLabel)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Split video into multiple videos with retimed subtitles"))
        self.label.setText(_translate("Dialog", "Video"))
        self.chooseVideoButton.setText(_translate("Dialog", "Choose file"))
        self.label_2.setText(_translate("Dialog", "Subtitle"))
        self.chooseSubtitleButton.setText(_translate("Dialog", "Choose file"))
        self.durationTimeEdit.setDisplayFormat(_translate("Dialog", "hh:mm:ss"))
        self.label_4.setText(_translate("Dialog", "Output folder"))
        self.chooseFolderButton.setText(_translate("Dialog", "Choose folder"))
        self.processButton.setText(_translate("Dialog", "Process"))
        self.label_3.setText(_translate("Dialog", "Length of each clip"))
